/**
 * Central registry of all auditable action keys in the system.
 * Used by audit writers and audit log filtering UI.
 */

export const AUDIT_ACTIONS = {
  // Verification & Analyst
  FIELD_VERIFIED: "FIELD_VERIFIED",
  FIELD_OVERRIDDEN: "FIELD_OVERRIDDEN",
  DISCREPANCY_RESOLVED: "DISCREPANCY_RESOLVED",
  DISCREPANCY_FLAGGED: "DISCREPANCY_FLAGGED",
  FRAUD_SIGNAL_DISPOSITIONED: "FRAUD_SIGNAL_DISPOSITIONED",
  RECEIPT_VERIFIED: "RECEIPT_VERIFIED",
  RECEIPT_REJECTED: "RECEIPT_REJECTED",
  MEDIA_MODERATED: "MEDIA_MODERATED",
  VALUATION_OVERRIDDEN: "VALUATION_OVERRIDDEN",
  LISTING_STATUS_CHANGED: "LISTING_STATUS_CHANGED",
  LISTING_PUBLISHED: "LISTING_PUBLISHED",
  LISTING_INFO_REQUESTED: "LISTING_INFO_REQUESTED",
  LISTING_REJECTED: "LISTING_REJECTED",
  LISTING_ESCALATED: "LISTING_ESCALATED",
  LISTING_ESCALATION_CLEARED: "LISTING_ESCALATION_CLEARED",

  // Admin Overrides & Workflow Intervention
  ADMIN_OVERRIDE_LISTING_STATUS: "ADMIN_OVERRIDE_LISTING_STATUS",
  ADMIN_REASSIGN_ANALYST: "ADMIN_REASSIGN_ANALYST",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_PII_REVEALED: "USER_PII_REVEALED",
  POLICY_VERSIONED: "POLICY_VERSIONED",
  POLICY_UPDATED: "POLICY_UPDATED",
  JOB_RETRIED: "JOB_RETRIED",

  // KYC & Users
  KYC_REVIEWED: "KYC_REVIEWED",

  // Payments & Deals
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCEEDED: "PAYMENT_SUCCEEDED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_RETRIED: "PAYMENT_RETRIED",
  PAYMENT_RECONCILED: "PAYMENT_RECONCILED",
  PAYMENT_EXCEPTION_RECORDED: "PAYMENT_EXCEPTION_RECORDED",
  DEAL_CREATED: "DEAL_CREATED",
  DEAL_COMPLETED: "DEAL_COMPLETED",
  MILESTONE_COMPLETED: "MILESTONE_COMPLETED",
  OFFER_CREATED: "OFFER_CREATED",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  OFFER_COUNTERED: "OFFER_COUNTERED",
  OFFER_DECLINED: "OFFER_DECLINED",

  // Security & Boundary
  ACCESS_DENIED: "ACCESS_DENIED",
} as const;

export type AuditActionKey = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
